### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by david-vendel** [CodingGarden/react-typescript-guestbook#1]
After fresh install, yarn install, yarn start I got:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:317:13)
    at D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:335:12)
    at next (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:317:13)
    at D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:335:12)
    at next (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (D:\OneDrive\GitHub\react-typescript-guestbook\node_modules\express\lib\router\layer.js:95:5)

**Comment by w3bdesign** [comment]
Make sure the path argument sent to validateString in internal/validators.js is not empty or undefined. 

It may also help to define a default value.

It's hard to help any further without seeing any actual code.
